/*seleccionar la tabla en la que vamos a trabajar*/
USE ventas_jugos;

/*crear tabla vendedor*/
CREATE TABLE tb_vendedor(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
DE_VACACIONES BIT(1) NULL,
PRIMARY KEY (MATRICULA)
);

/*crear tabla producto*/
CREATE TABLE  tb_producto(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

/*crea tabla clientes*/
CREATE TABLE clientes(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) DEFAULT NULL,
DIRECCION VARCHAR(150) DEFAULT NULL,
BARRIO VARCHAR(50) DEFAULT NULL,
CIUDAD VARCHAR(50) DEFAULT NULL,
ESTADO VARCHAR(45) DEFAULT NULL,
CP VARCHAR(8) DEFAULT NULL,
FECHA_NACIMIENTO DATE DEFAULT NULL,
EDAD INT(2) DEFAULT NULL,
SEXO VARCHAR(1) DEFAULT NULL,
LIMITE_CREDITO FLOAT DEFAULT NULL,
VOLUMEN_COMPRA FLOAT DEFAULT NULL,
PRIMERA_COMPRA BIT(1) DEFAULT NULL,
PRIMARY KEY (DNI)
);