SELECT *
FROM tabla_de_productos;

SELECT *
FROM tabla_de_productos
ORDER BY PRECIO_DE_LISTA;

SELECT *
FROM tabla_de_productos
ORDER BY PRECIO_DE_LISTA DESC;

SELECT *
FROM tabla_de_productos
ORDER BY NOMBRE_DEL_PRODUCTO;

SELECT *
FROM tabla_de_productos
ORDER BY ENVASE DESC, NOMBRE_DEL_PRODUCTO ASC;