SELECT CURRENT_TIMESTAMP() AS RESULTADO;

SELECT CONCAT("la fecha y hora de hoy son: ", CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT("la fecha y hora de hoy son: ", 
DATE_FORMAT(CURRENT_TIMESTAMP(), "%W, %d/%m/%Y, a las %T")) AS RESULTADO;

SELECT CONVERT(21.113, CHAR) AS RESULTADO;

SELECT SUBSTRING(CONVERT(21.1345, CHAR), 3, 1) AS RESULTADO;

SELECT
	CONCAT("el cliente ", TC.NOMBRE, " facturo ",
    CONVERT(SUM(IFa.CANTIDAD * IFa.precio), CHAR(20)),
    " en el ano ", CONVERT(YEAR(F.FECHA_VENTA), CHAR(20))) AS FRASE
FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
INNER JOIN tabla_de_clientes TC ON F.DNI = TC.DNI
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY TC.NOMBRE, YEAR(FECHA_VENTA);
