USE jugos_ventas;

/*cantidad vendida por sabor ano 2016*/
SELECT 
	P.SABOR,
    SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS ANO
FROM tabla_de_productos P
INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC;

/*cantidad total por ano*/
SELECT 
    SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS ANO
FROM tabla_de_productos P
INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA);


/*uniendo ambas consultas*/
SELECT *
FROM(
SELECT 
	P.SABOR,
    SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS ANO
FROM tabla_de_productos P
INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC
) VENTAS_SABOR
INNER JOIN(
SELECT 
    SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS ANO
FROM tabla_de_productos P
INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)
) VENTA_TOTAL
ON VENTA_TOTAL.ANO = VENTAS_SABOR.ANO;


/*obtener porcentaje*/
SELECT 
	VENTAS_SABOR.SABOR,
    VENTAS_SABOR.ANO,
    VENTAS_SABOR.CANTIDAD_TOTAL,
    ROUND((VENTAS_SABOR.CANTIDAD_TOTAL/VENTA_TOTAL.CANTIDAD_TOTAL)*100, 2) AS PORCENTAJE
FROM(
SELECT 
	P.SABOR,
    SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS ANO
FROM tabla_de_productos P
INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC
) VENTAS_SABOR
INNER JOIN(
SELECT 
    SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS ANO
FROM tabla_de_productos P
INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)
) VENTA_TOTAL
ON VENTA_TOTAL.ANO = VENTAS_SABOR.ANO
ORDER BY VENTAS_SABOR.CANTIDAD_TOTAL DESC;

