SELECT CURRENT_TIMESTAMP() AS RESULTADO;

SELECT CONCAT("la fecha y hora de hoy son: ", CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT("la fecha y hora de hoy son: ", 
DATE_FORMAT(CURRENT_TIMESTAMP(), "%W, %d/%m/%Y, a las %T")) AS RESULTADO;

SELECT CONVERT(21.113, CHAR) AS RESULTADO;

SELECT SUBSTRING(CONVERT(21.1345, CHAR), 3, 1) AS RESULTADO;