USE jugos_ventas;

SELECT *
FROM tabla_de_vendedores;

SELECT *
FROM facturas;

SELECT *
FROM tabla_de_vendedores A
INNER JOIN
facturas B
ON A.MATRICULA = B.MATRICULA;

SELECT 
	A.NOMBRE,
    B.MATRICULA,
    COUNT(*)
FROM tabla_de_vendedores A
INNER JOIN
facturas B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.NOMBRE, B.MATRICULA;

SELECT 
	A.NOMBRE,
    B.MATRICULA,
    COUNT(*)
FROM tabla_de_vendedores A, facturas B
WHERE A.MATRICULA = B.MATRICULA
GROUP BY A.NOMBRE, B.MATRICULA;

SELECT
	YEAR(FECHA_VENTA),
    SUM(CANTIDAD * PRECIO) AS FACTURACION
FROM facturas F
INNER JOIN
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
GROUP BY YEAR (FECHA_VENTA);