SELECT (34+346-67)/15 * 29 AS RESULTADO;

SELECT CEILING(23.5266);

SELECT FLOOR(23.99999);

SELECT RAND() AS RESULTADO;

SELECT ROUND(243.564, 2);

SELECT 
	NUMERO,
    CANTIDAD,
    PRECIO,
    CANTIDAD * PRECIO AS FACTURACION
FROM items_facturas;

SELECT 
	NUMERO,
    CANTIDAD,
    PRECIO,
    ROUND(CANTIDAD * PRECIO, 2) AS FACTURACION
FROM items_facturas;
