USE jugos_ventas;

SELECT 
	P.SABOR,
    SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS ANO
FROM tabla_de_productos P
INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
WHERE (F.FECHA_VENTA) = 2016
GROUP BY
	P.SABOR,
    YEAR(F.FECHA_VENTA);
