SELECT *
FROM facturas;

SELECT *
FROM items_facturas;

SELECT 
	F.DNI,
    F.FECHA_VENTA,
    IFa.CANTIDAD
FROM facturas F
INNER JOIN items_facturas IFa
	ON F.NUMERO = IFa.NUMERO;
    
SELECT 
	F.DNI,
    DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_ANO,
    IFa.CANTIDAD
FROM facturas F
INNER JOIN items_facturas IFa
	ON F.NUMERO = IFa.NUMERO;
    
/* cantidad de ventas por mes para cada cliente*/
SELECT 
	F.DNI,
    DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_ANO,
    SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA
FROM facturas F
INNER JOIN items_facturas IFa
	ON F.NUMERO = IFa.NUMERO
GROUP BY
	F.DNI, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y");
    
/* limite de ventas por cliente (VOLUMEN EN DECILITROS)*/
SELECT * 
FROM tabla_de_clientes TC;   

SELECT 
	DNI,
    NOMBRE,
    VOLUMEN_DE_COMPRA
FROM tabla_de_clientes TC;

/*combinar consultas anteriores*/
SELECT 
	F.DNI,
    TC.NOMBRE,
    DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_ANO,
    SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA,
    MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
FROM facturas F
INNER JOIN items_facturas IFa
	ON F.NUMERO = IFa.NUMERO
 INNER JOIN tabla_de_clientes TC
	ON TC.DNI = F.DNI
GROUP BY
	F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y");

/*subconsulta*/    
SELECT 
	A.DNI,
    A.NOMBRE,
    A.MES_ANO,
    A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA
FROM (
	SELECT 
	F.DNI,
    TC.NOMBRE,
    DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_ANO,
    SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA,
    MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
	FROM facturas F
	INNER JOIN items_facturas IFa
		ON F.NUMERO = IFa.NUMERO
	INNER JOIN tabla_de_clientes TC
		ON TC.DNI = F.DNI
	GROUP BY
		F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y")
) A;
    

SELECT 
	A.DNI,
    A.NOMBRE,
    A.MES_ANO,
    A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
	CASE
		WHEN A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA < 0 THEN 'Venta Valida'
        ELSE 'Venta Invalida'
	END AS STATUS_VENTA
FROM (
	SELECT 
	F.DNI,
    TC.NOMBRE,
    DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_ANO,
    SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA,
    MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
	FROM facturas F
	INNER JOIN items_facturas IFa
		ON F.NUMERO = IFa.NUMERO
	INNER JOIN tabla_de_clientes TC
		ON TC.DNI = F.DNI
	GROUP BY
		F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y")
) A;
